# Generated by Django 3.2.7 on 2022-02-18 20:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.CharField(max_length=500)),
                ('foto', models.ImageField(blank=True, upload_to='imagenes')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=256)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 2, 18, 20, 41, 50, 428091, tzinfo=utc))),
                ('subir', models.ImageField(upload_to='imagenes')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paradise_app.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrella', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paradise_app.post')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paradise_app.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(blank=True, max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paradise_app.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment', models.CharField(max_length=256)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paradise_app.perfil')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paradise_app.post')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 2, 18, 20, 41, 50, 428091, tzinfo=utc))),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paradise_app.perfil')),
                ('publications', models.ManyToManyField(to='paradise_app.Post')),
            ],
        ),
    ]
