# Generated by Django 3.2.7 on 2022-02-18 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('paradise_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 20, 41, 53, 769087, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 20, 41, 53, 769087, tzinfo=utc)),
        ),
    ]
